name: Publish to PyPI
on: 
  pull_request:
    branches:
      - master

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - run: poetry run pytest
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Create version tag
        run: poetry version patch
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::$(poetry version -s)
      - name: Create git tag
        run: git tag ${{ steps.get_version.outputs.version }}
      - name: Push tag
        run: git push origin ${{ steps.get_version.outputs.version }}
      - name: Publish package
        run: poetry publish --build